spring.application.name=notificacao

spring.profiles.active=${APP_PROFILE:test}
spring.jpa.open-in-view=false

server.port=8082

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

logging.level.com.junior.notificacao=INFO
logging.level.org.springframework.amqp=WARN
logging.level.org.springframework.rabbit=WARN