spring.application.name=conta-transf
spring.profiles.active=${APP_PROFILE:test}
spring.jpa.open-in-view=false

server.port=8081
cliente.service.url=${CUSTOMER_SERVICE_URL:http://localhost:8080}

logging.level.feign=INFO
logging.level.com.junior.conta_transf.integration=DEBUG
logging.level.com.junior.conta_transf.integration.IntegrationClient=DEBUG

# OpenFeign + CircuitBreaker
spring.cloud.openfeign.circuitbreaker.enabled=true
spring.cloud.openfeign.circuitbreaker.alphanumeric-ids.enabled=true

# Actuator
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.health.circuitbreakers.enabled=true

# Resilience4j - CircuitBreaker
resilience4j.circuitbreaker.instances.IntegrationClientfindByIdLong.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.IntegrationClientfindByIdLong.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.IntegrationClientfindByIdLong.slidingWindowSize=10
resilience4j.circuitbreaker.instances.IntegrationClientfindByIdLong.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.IntegrationClientfindByIdLong.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.IntegrationClientfindByIdLong.failureRateThreshold=50
resilience4j.circuitbreaker.instances.IntegrationClientfindByIdLong.waitDurationInOpenState=20s
resilience4j.circuitbreaker.instances.IntegrationClientfindByIdLong.automaticTransitionFromOpenToHalfOpenEnabled=true

# Resilience4j - TimeLimiter
resilience4j.timelimiter.instances.IntegrationClientfindByIdLong.timeoutDuration=2s
resilience4j.timelimiter.instances.IntegrationClientfindByIdLong.cancelRunningFuture=true

# Resilience4j - Retry
resilience4j.retry.instances.clienteRetry.maxAttempts=3
resilience4j.retry.instances.clienteRetry.waitDuration=500ms
resilience4j.retry.instances.clienteRetry.enableExponentialBackoff=true
resilience4j.retry.instances.clienteRetry.exponentialBackoffMultiplier=2