spring.application.name=conta-transf
spring.profiles.active=${APP_PROFILE:test}
spring.jpa.open-in-view=false

server.port=8081
cliente.service.url=${CUSTOMER_SERVICE_URL:http://localhost:8080}

logging.level.feign=INFO
logging.level.com.junior.conta_transf.integration=DEBUG
logging.level.com.junior.conta_transf.integration.IntegrationClient=DEBUG