spring.application.name=cliente

spring.profiles.active=${APP_PROFILE:test}
spring.jpa.open-in-view=false

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest